/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SignUpIndexRouteImport } from './routes/sign-up/index'
import { Route as LayoutTeleopRouteImport } from './routes/_layout/teleop'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutFieldsRouteImport } from './routes/_layout/fields'
import { Route as LayoutDevicesRouteImport } from './routes/_layout/devices'

const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpIndexRoute = SignUpIndexRouteImport.update({
  id: '/sign-up/',
  path: '/sign-up/',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutTeleopRoute = LayoutTeleopRouteImport.update({
  id: '/teleop',
  path: '/teleop',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutFieldsRoute = LayoutFieldsRouteImport.update({
  id: '/fields',
  path: '/fields',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutDevicesRoute = LayoutDevicesRouteImport.update({
  id: '/devices',
  path: '/devices',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/devices': typeof LayoutDevicesRoute
  '/fields': typeof LayoutFieldsRoute
  '/settings': typeof LayoutSettingsRoute
  '/teleop': typeof LayoutTeleopRoute
  '/sign-up': typeof SignUpIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/devices': typeof LayoutDevicesRoute
  '/fields': typeof LayoutFieldsRoute
  '/settings': typeof LayoutSettingsRoute
  '/teleop': typeof LayoutTeleopRoute
  '/sign-up': typeof SignUpIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_layout': typeof LayoutRouteWithChildren
  '/_layout/devices': typeof LayoutDevicesRoute
  '/_layout/fields': typeof LayoutFieldsRoute
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/teleop': typeof LayoutTeleopRoute
  '/sign-up/': typeof SignUpIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/devices' | '/fields' | '/settings' | '/teleop' | '/sign-up'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/devices' | '/fields' | '/settings' | '/teleop' | '/sign-up'
  id:
    | '__root__'
    | '/'
    | '/_layout'
    | '/_layout/devices'
    | '/_layout/fields'
    | '/_layout/settings'
    | '/_layout/teleop'
    | '/sign-up/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LayoutRoute: typeof LayoutRouteWithChildren
  SignUpIndexRoute: typeof SignUpIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up/': {
      id: '/sign-up/'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/teleop': {
      id: '/_layout/teleop'
      path: '/teleop'
      fullPath: '/teleop'
      preLoaderRoute: typeof LayoutTeleopRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/fields': {
      id: '/_layout/fields'
      path: '/fields'
      fullPath: '/fields'
      preLoaderRoute: typeof LayoutFieldsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/devices': {
      id: '/_layout/devices'
      path: '/devices'
      fullPath: '/devices'
      preLoaderRoute: typeof LayoutDevicesRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutDevicesRoute: typeof LayoutDevicesRoute
  LayoutFieldsRoute: typeof LayoutFieldsRoute
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutTeleopRoute: typeof LayoutTeleopRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutDevicesRoute: LayoutDevicesRoute,
  LayoutFieldsRoute: LayoutFieldsRoute,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutTeleopRoute: LayoutTeleopRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LayoutRoute: LayoutRouteWithChildren,
  SignUpIndexRoute: SignUpIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
